cooldown:
  # The cooldown to send marriage requests
  request: 5 # minutes

  # The cooldown to marry again after a divorce
  divorce: 60 # minutes

# How much a marriage should cost, this will only be withdrawn when the other person accepts the request
# Do not change!
marriage-cost: 10000

# Some commands are not fully tested and may have bugs. Disable them by setting this to false
beta-testing: false

# The prefix for the broadcast when people marry
broadcast-prefix: '&b&l[&2&lMarriageEC&b&l]'

# Smites the partner upon the death of his/her partner
smite-on-partner-dead: true

# Unlock the following /partner <command> after having a bank value of...
unlock:
  command:
    seen: 0
    info: 1000
    chat: 5000
    tp: 10000
    home: 50000
    chest: 75000
  perk:
    prefix: 0
    login-message: 15000
    teleport-effects: 25000
    no-smite-on-partner-dead: 40000
    hearts: 60000

# Homes, shared money and last seen are linked per server name
server_name: default

# MySQL
database: DBname
host: localhost
port: 3306
user: pi
password: myUberPass
table: marriage
servers_table: marriage_servers