name: Marriage
version: 0.2-BETA
description: Allows players to marry
author: TPNils
website: https://github.com/spyproof
main: be.spyproof.marriage.Marriage
depend: [Vault, Herochat]
commands:
  marry:
    description: Marry commands
    alliases: Marriage
  admmarry:
    description: Admin marry commands
  partner:
    description: Marriage perks

