name: MarriageEC
version: 1.1
description: Allows players to marry
author: TPNils & Idlehumor
website: https://github.com/spyproof
main: be.spyproof.marriage.Marriage
depend: [Vault]
softdepend: [Herochat, Essentials, EffectLib, WorldGuard]
commands:
  marry:
    description: Marry commands
    alliases: Marriage
  admmarry:
    description: Admin marry commands
  partner:
    description: Marriage perks

